### ISSUE TITLE
How can i make dataset?

### ISSUE THREAD

**Issue by lsy-92** [cviviers/YOLOv5-6D-Pose#9]
Thanks for your amazing job.

i make a custom dataset. but my training is wrong. my loss is 0.
so i want to ask for dataset.

Do i  normalized Object Size Range by image width and height?

And Why are the rotation vector and translation vector missing from the labels in the LINEMOD dataset?

Thanks

Label Format
Each of the 21 numbers corresponds to specific data points: 0. Class Label

Centroid Coordinates: x0 (x-coordinate), y0 (y-coordinate)
Corner Coordinates: From x1, y1 (first corner) to x8, y8 (eighth corner)
Object Size Range: x range, y range
Focal length x
Focal length y
Sensor width (in optical this can just be the image size)
Sensor height (in optical this can just be the image size)
Focal offset x (u0)
Focal offset y (v0)
Image width
Image height
Object rotation vector (Rodriques) [3x1]
Object translation vector [3x1]
Note: Coordinates are normalized by image width and height (x / image_width, y / image_height).

**Comment by cviviers** [comment]
Hi @lsy-92,

Yes, thanks for pointing this out. The object size range / object width and height should also be normalized by the image width & height. If you are using the `create_label` function in the provided code it will do this correctly based off of the object keypoints. 

I will update the description to make this clear. 

The rotation vector and translation vector is not used in the code at the moment. I added it so that I can do a check on predicted poses later on or if I wanted to switch to an alternative approach that does direct pose estimation, such as EfficientPose. Feel free to exclude it if you like.

**Comment by lsy-92** [comment]
Thanks for your answer.

I make my dataset using Blender. 

i was modeling my object, and extract necessary information using Blender.

But i think it is not correct.

If I want to make custom dataset for using your project, should i use your creat_dataset.ipynb?

Thanks.

**Comment by cviviers** [comment]
Blender is definitely the correct starting point. Do you plan on acquiring the poses in blender as well or do you have a real object that you want to capture images of? I used blender to create 3D models of all the objects (exported as .ply files). Acquire real poses using the description in create_dataset.ipynb, and in addition, project the 3D model onto the real images to get fine-grained masks to train with. This will help immensely with robustness of the model.

**Comment by lsy-92** [comment]
I get my all information like poses and 3d bbox coordinates using Pytorch3d and Blender. I think that method is a little bit cheating, but i think it is possible. But it doesn't work.

**Comment by lsy-92** [comment]
I'm sorry for asking too many questions.

I try detecting Linemod object cat image using pretrained yolov5s.pt.

Although some images are not object detected, yolov5-6d-pose Model train well.

But My Custom Dataset can't train because of in PoseLoss

    n = b.shape[0]  # number of targets
            if n:
n = 0. 

What am I doing wrong?

Thanks.

**Comment by cviviers** [comment]
Hi @lsy-92,

It is no problem to ask questions :)
If you show me some examples of your blender setup and data being generated I can see if there is anything wrong.

For clarification, the YOLOv5s, YOLOv5x are COCO pretrained. We only use them to initialize the model weights for pose estimation training. Use the linemod object weights for pose estimation.

The error you describe seems like there is no label in the label file for that particular image. To make sure your images and labels are correct, before and after augmentation, you can change [line 741](https://github.com/cviviers/YOLOv5-6D-Pose/blob/bdbf4604dcf507a556228790232166a6b2932124/utils/datasets.py#L741C8-L741C18)  to True. This will display the images.

**Comment by lsy-92** [comment]
I use pytorch3d.

`mesh_R_T = []
            for i, mesh in enumerate(meshes):
                translation = trans_3d[rand_3d[i]].to(device)
                rotation = rotat_3d[i].to(device)
                verts = mesh.verts_packed() @ rotation.T
                verts = verts + translation.unsqueeze(0)
                faces = mesh.faces_packed()
                mesh = Meshes(verts=[verts], faces=[faces], textures=mesh.textures)

                mesh_R_T.append(mesh)

            mesh_scene = join_meshes_as_scene(mesh_R_T, include_textures=True)
            mesh_views = mesh_scene.extend(num_views)

            dist = torch.rand(num_views) * (d1 - d0) + d0
            azim = torch.rand(num_views) * (a1 - a0) + a0
            elev = torch.rand(num_views) * (e1 - e0) + e0
            R, T = look_at_view_transform(dist=dist, elev=elev, azim=azim,device=device)

            
            camera = FoVPerspectiveCameras(device=device, R=R, T=T).to(device)
            projection_matrices = camera.get_projection_transform().get_matrix()
            lights = pytorch3d.renderer.PointLights(device=device)
            blend_params = BlendParams(1e-4, 1e-4, (0, 0, 0))         

            rgb_settings = RasterizationSettings(image_size=img_size, blur_radius=0.0, faces_per_pixel=4, bin_size=0)
            rgb_rasterizer = MeshRasterizer(cameras=camera, raster_settings=rgb_settings)
            rgb_shader = SoftPhongShader(device=device, cameras=camera, lights=lights, blend_params=blend_params)
            rgb_renderer = MeshRenderer(rasterizer=rgb_rasterizer, shader=rgb_shader)
            rgb_images = rgb_renderer(mesh_views, cameras=camera, lights=lights)
            rgb_targets = [rgb_images[i, ..., :3] for i in range(num_views)]

            depth_raster_settings = RasterizationSettings(image_size=img_size, blur_radius=0.0, faces_per_pixel=1, bin_size=0)
            depth_rasterizer = MeshRasterizer(cameras=camera, raster_settings=depth_raster_settings)
            depth_fragments = depth_rasterizer(mesh_views, camera=camera)
            depth_zbuf = depth_fragments.zbuf
            depth_images = depth_zbuf.min(dim=-1).values

            seg_raster_settings = RasterizationSettings(image_size=img_size, blur_radius=0.0, faces_per_pixel=1, bin_size=0)
            seg_rasterizer = MeshRasterizer(cameras=camera, raster_settings=seg_raster_settings)
            seg_shader = HardFlatShader(device=device, cameras=camera, lights=lights, blend_params=blend_params)
            seg_renderer = MeshRenderer(rasterizer=seg_rasterizer, shader=seg_shader)`
this is how i make JPEGimages and mask.
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/f4ec0089-ac42-420c-9215-cf9ec63c1b32)
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/2896357a-8892-4fd6-940e-cb8bc3dbeffb)

Then i make label.
`label = create_label(1, origin_x, origin_y, bbox_3d_list, x_range, y_range, fx, fy, img_size, img_size, u0, v0, img_size, img_size, RRR, TTT)`

1 
0.575 0.357812 center x, y

0.58872 0.364275 0.633229 0.365654 0.569569 0.487762 0.613545 0.482464 0.533243 0.352083 0.57823 0.354027 0.517102 0.469103 0.561416 0.465034 x1, y1 (first corner) to x8, y8 (eighth corner)
0.854262 1.501989 x range, y range
1.732051 1.732051 focal x, y
640 640 img_size
0.0 0.0 u0,v0
640 640 img_size

and visualization this 3d bbox like this.
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/24333301-0e30-4ed9-a541-6255bbc1fd51)

and I make this files like Linemod Dataset.
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/ccbe35e0-bfdd-46d4-9146-794629914a70)

**Comment by cviviers** [comment]
Having a quick look the only issue I can see is that u0, v0 (camera focal point) should be 320 and 320, not 0, assuming you have a prefect camera. 

Can you make a projection of the 3D bounding box back onto the image and see if it aligns with your object? There is some code for that in the data_curation.

**Comment by lsy-92** [comment]
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/17fd65e4-cef9-4f20-b0af-6a96d9d5b979)
this is my projection matrix.
and this is my 3d bbox code.
`def calculate_points_3db_box(point, R, T, projected_matrix, camera, img_shape=(256, 256)):
    point = point.view(1, 1, 3)
    origin_xyz = point[:, :, :3]
    transformed_origin_xyz = torch.bmm(origin_xyz, R) + T.unsqueeze(1)
    transformed_origin = torch.cat([transformed_origin_xyz, torch.ones_like(transformed_origin_xyz[:, :, :1])], dim=-1)
    projected_origin = torch.bmm(transformed_origin, projected_matrix.transpose(1, 2))
    projected_origin = projected_origin.squeeze(1)
    print("projected_origin 2 : " ,projected_origin)
    projected_origin_ndc = projected_origin[:, :3] / projected_origin[:, 3:]
    print("projected_origin_ndc 2 : " ,projected_origin_ndc)
    x_pixel = (projected_origin_ndc[:, 0]) + img_shape[0] / 2
    y_pixel = (projected_origin_ndc[:, 1]) + img_shape[1] / 2
    print(f"3D Box Points -> X: {x_pixel}, Y: {y_pixel}")  # 디버깅 정보 출력
    return x_pixel, y_pixel
`
`min_x, min_y, min_z = sampled_points.min(dim=1).values.squeeze()
                    max_x, max_y, max_z = sampled_points.max(dim=1).values.squeeze()
                    bbox_3d = torch.tensor([[min_x, min_y, min_z], [max_x, min_y, min_z], [min_x, max_y, min_z], [max_x, max_y, min_z], [min_x, min_y, max_z], [max_x, min_y, max_z], [min_x, max_y, max_z], [max_x, max_y, max_z]], dtype=torch.float32, device=device)

                    bbox_3d_list = []
                    origin_x = (bbox[0] + bbox[2]) / 2
                    origin_y = (bbox[1] + bbox[3]) / 2
                    for i in range(8):
                        x, y = calculate_points_3db_box(bbox_3d[i], RRR, TTT, projection_matrices[0].unsqueeze(0), camera=camera, img_shape=(640, 640))
                        bbox_3d_list.append([x, y])

                    seg_pil = seg_pil.convert("RGBA")
                    draw = ImageDraw.Draw(seg_pil)
                    edges = [
                        (0, 1), (1, 3), (3, 2), (2, 0),
                        (4, 5), (5, 7), (7, 6), (6, 4),
                        (0, 4), (1, 5), (2, 6), (3, 7)
                    ]

                    for edge in edges:
                        draw.line(
                            (bbox_3d_list[edge[0]][0], bbox_3d_list[edge[0]][1], bbox_3d_list[edge[1]][0], bbox_3d_list[edge[1]][1]),
                            fill="red",
                            width=2
                        )`

**Comment by cviviers** [comment]
Hi @lsy-92,

I am currently away for a few days, so can't execute any code. Have you tried visualizing the 3D bounding box projection onto your images? Do they align with the object you are interested in? If you visualize it with the dataloader in YOLOv5-6D and they look good, then you can assume the data you have created is in the correct format for training.

**Comment by lsy-92** [comment]
Thank you for your reply during the schedule.

I check dataloader, and save test.png.

![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/30c60719-e38a-4978-bdc6-2d27d3c76132)

so i think it looks good.

but always loss is [0](torch.tensor).

this is my output log.
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to runs/train/exp70
Starting training for 5000 epochs...
     Epoch   gpu_mem     l_obj     l_box     l_cls n_targets  img_size
  0%|                                                                                                                                                                   | 0/28 [00:00<?, ?it/s]
[34m[1mautoanchor: [39m[22mthr=0.25: 1.0000 best possible recall, 9.00 anchors past thr
[34m[1mautoanchor: [39m[22mn=9, img_size=640, metric_all=0.994/0.999-mean/best, past_thr=0.994-mean: 546,963,  546,969,  547,973,  546,978,  547,977,  547,978,  546,980,  546,983,  547,981
[34m[1mautoanchor: [39m[22mNew anchors saved to model. Update model *.yaml to use these anchors in the future.
pred :  3
targets :  torch.Size([32, 22])
lbox 1 : tensor([0.], device='cuda:0')
Layer 0, anchor_t: 4.0, matched targets: 3
Layer 1, anchor_t: 4.0, matched targets: 3
Layer 2, anchor_t: 4.0, matched targets: 3
p : 3
 n :  9
l2_dist:  tensor(10.20634, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.00995], device='cuda:0', grad_fn=<AddBackward0>)
 n :  9
l2_dist:  tensor(6.61466, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.03554], device='cuda:0', grad_fn=<AddBackward0>)
 n :  9
l2_dist:  tensor(5.59261, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.11948], device='cuda:0', grad_fn=<AddBackward0>)
self.hyp['box'] =  1.5
loss = lbox + lcls
loss :  tensor([5.73502], device='cuda:0', grad_fn=<MulBackward0>)

    0/4999     2.39G     2.175    0.1792         0        32       640:   4%|██▉                                                                                | 1/28 [00:07<03:22,  7.50s/it]
pred :  3
targets :  torch.Size([32, 22])
lbox 1 : tensor([0.], device='cuda:0')
Layer 0, anchor_t: 4.0, matched targets: 1
Layer 1, anchor_t: 4.0, matched targets: 0
No targets matched for this layer.
Layer 2, anchor_t: 4.0, matched targets: 0
No targets matched for this layer.
p : 3
 n :  3
l2_dist:  tensor(10.24166, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.01166], device='cuda:0', grad_fn=<AddBackward0>)
 n :  0
 n :  0
self.hyp['box'] =  1.5
loss = lbox + lcls
loss :  tensor([0.55961], device='cuda:0', grad_fn=<MulBackward0>)


    0/4999     7.21G     2.175    0.1123         0        32       640:  11%|████████▉                                                                          | 3/28 [00:12<01:28,  3.53s/it]
pred :  3
targets :  torch.Size([32, 22])
lbox 1 : tensor([0.], device='cuda:0')
Layer 0, anchor_t: 4.0, matched targets: 9
Layer 1, anchor_t: 4.0, matched targets: 6
Layer 2, anchor_t: 4.0, matched targets: 6
p : 3
 n :  27
l2_dist:  tensor(8.90784, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.00896], device='cuda:0', grad_fn=<AddBackward0>)
 n :  18
l2_dist:  tensor(5.03969, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.02829], device='cuda:0', grad_fn=<AddBackward0>)
 n :  18
l2_dist:  tensor(4.34330, device='cuda:0', grad_fn=<MeanBackward0>)
lbox 2 : tensor([0.09337], device='cuda:0', grad_fn=<AddBackward0>)
self.hyp['box'] =  1.5
loss = lbox + lcls
loss :  tensor([4.48168], device='cuda:0', grad_fn=<MulBackward0>)
    0/4999     7.21G     2.175    0.1123         0        32       640:  11%|████████▉                                                                          | 3/28 [00:14<02:01,  4.84s/it]
Traceback (most recent call last):
  File "YOLOv5-6D-Pose/train.py", line 551, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "YOLOv5-6D-Pose/train.py", line 329, in train
    scaler.scale(loss).backward()
  File "anaconda3/envs/yolopose/lib/python3.9/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "anaconda3/envs/yolopose/lib/python3.9/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by cviviers** [comment]
From the looks of it, your model is training. You only have 1 class right? So the classification loss is always 0.

**Comment by lsy-92** [comment]
I'm sorry for the poor explanation.

The loss that I said was zero is lbox + lcls.

but I solved the problem by raising anchor_t to 10.0.

Thanks.

**Comment by lsy-92** [comment]
Thank you for your suggestion.

I'd love to, but it's the team member's code. 

I think I can add it to the repo after the team member's paper is accepted.

And I have some problems.

Training is good, but center points are something wrong.

![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/1b93257e-840b-477e-beee-3311d80308f7)

In this case, can I know the exact value if I calculate the center point and Pose of the 3dbbox inversely?

Thanks.

**Comment by cviviers** [comment]
From the looks of it, the coordinate is on one of the sides of the object instead of the center. In all the object in Linemod and in the X-ray objects I made, the center of the object was at 0,0,0 and the 3D bounding box spaced around that. Example of a 1cm^3 3D cube would be: top left -0.5cm, -0.5cm, -0.5cm and bottom right 0.5cm, 0.5cm, 0.5cm.  This doesnt need to be the case, but just makes it a bit easier.

**Comment by lsy-92** [comment]
Thanks for your explanation.

If i use this model in real situation, Does the model still perform correctly if the resolution or camera parameters of the training data differ from actual input's?

Thansk.

**Comment by lsy-92** [comment]
Yes, that answer is absolutly I want.

I try my code changing FoVPerspectiveCameras to PerspectiveCamers.

If I get some good result, I upload my create dataset code.

Thanks

**Comment by lsy-92** [comment]
I have a new problem.

I'm creating a new code that can reflect camera parameters.

I check my 3d bbox and That is quite correct.

But when I check my 3ddbox while learning, it looks wrong. 

I don't know what the problem is.

![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/20405eb5-83ca-434e-b127-c2eef70e64c0)

![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/100773530/eef72b8e-6f66-493d-bc1d-6bb47a0cf8f8)

**Comment by lsy-92** [comment]
I have another question.

If there is one class, but there are multiple objects of the same class in an image, can I get multiple 3D bboxes?

Thank you always.

**Comment by cviviers** [comment]
Hey @lsy-92,

You can straightforwardly do that by increasing the max detection in the box_filter. [Here ](https://github.com/cviviers/YOLOv5-6D-Pose/blob/6b982c6043bb41ab53da804e8d09300ed5204261/test.py#L172) you can set the "max_det" to the number of objects and confidence you allow. Do be aware, compared to the non maximum suppression (NMS) in earlier YOLO models, there is no real filtering here (You could get two predictions for the exact same object on the exact same location). The grid cells at the different scales could have a high confidence for the same object. 

You could use the object bounding boxes in a NMS way to filter these, but I leave that to you :)

**Comment by lsy-92** [comment]
I want to test the pt file of this model on detection in yolov5. 
I want to know how much Feature Extractor is affected and how much it is affected in Pretrained epoch.
I'm considering domain gap, and I think this part should be solved.

**Comment by cviviers** [comment]
Hey @lsy-92,

Apologies for the late response. Yes, I think this will have to be slightly modified. The idea is to get the indices of the elements with predictions that matches the object you are currently trying to evaluate. So get all the predictions for that class (10+ now in your case) and introduce a new for loop to loop over each of them and evaluate the performance of each. You can possibly use the best score on each object as the matching score and discard the rest. 

I would like to learn more about the dataset/use case you have for this. Would be interesting for follow up research or some collaboration :)

**Comment by lsy-92** [comment]
It's been a while, so it's nice to meet you.

We are continuing to upgrade our dataset and apply it to the real world.

It's not easy yet.

I want to ask you a few things.

Why the anchors is 3 in config  Can't I use the anchors in the existing yolov5?

And I want to bring the head of yolov5 and compare how updated the Backbone is.

Finally, if I bring the checkpoint from yolov5 where I learned real and synth tomatoes, freeze the backbone, and then learn, will I be able to get a good keypoint?

Thanks

**Comment by cviviers** [comment]
You should be able to freely change the number of anchors or even increase the number of heads. Many of the YOLOv5 settings are still compatible with YOLOv5-6D. They are currently just set to what worked for me and produced stable and consistent results.

As for the freezing of the backbone - I am not sure. It is worth a shot. Coming from COCO pretrained weights to the LINEMOD setting I thought the model would converge much faster, but ended up requiring a lot of training. A possible explanation is that for the object detection task there is no difference in object features that are on the left or right, it only cares for features belonging to the object. In pose estimation, this matters. Also, this is to be confirmed :) please keep me updated with your progress.

**Comment by lsy-92** [comment]
I'm sorry for the late response.

I was continuing to conduct experiments.

I wonder if you only update after pretrained epoch for l_obj.

We also modified the camera parameter.json quite significantly, but the distortion of the detection results was the same.

Does it not affect the outcome of Detection?

 Thanks

**Comment by assia855** [comment]
Hi @lsy-92  how did you success to have the mask and the exact bounding box please?
Thanks in advance for any suggestion.

**Comment by lsy-92** [comment]
Hi, @assia855. 

The method I did is render a 3D modeling file via pytorch3d, and this is a topic I'm working on, so it's hard to reveal the detailed code yet.

However, I can tell you the other way I thought.

When I make a mask, the main thing I use is cvat. For cvat, segmentation can be done using the SAM model, which can be used to create mask images.

And how to get 3D BBox is projected and obtained, or try this GitHub.

https://github.com/CongliangLi/LabelImg3D/#Dateset

Thanks.

**Comment by lsy-92** [comment]
Hi @assia855 . Sorry I'm late.

First, set each vertex of the 3D object model, typically using the eight corner points of the 3D bounding box (3D BBox). Use the pose information (R, T) to transform the 3D points into the camera coordinate system. Project the transformed 3D points into 2D image coordinates using the camera's intrinsic calibration matrix.

**Comment by lsy-92** [comment]
Hi, @cviviers . 
I'm having a hard time with the metric.

The prediction results saved during learning look very good.
But ACC is getting zero.
I don't know how the validation and test have the same path, but this is how it comes out.

![image](https://github.com/user-attachments/assets/6383afd5-59a7-4b11-8e13-51196ff17078)

![image](https://github.com/user-attachments/assets/daa7c4af-3df9-4124-91f4-9571b7b7998e)

Thanks

**Comment by cviviers** [comment]
Hi @lsy-92,
Yes, the metrics are extremely strict. ACC is a 5 pixel 2D reprojection metric, i.e. if the all the keypoints summed error is < 5 pixels. Also the 3D accuracy by default is 10% of the object width. This makes it increasingly more difficult for smaller objects. feel free to relax the metric if you think it is not necessary for your task. 
This is also why I spent most of the time in getting accurate datapoints. you can imagine if there is a small inconsistency in your ground-truth labels how it can hurt these strict metrics.

**Comment by lsy-92** [comment]
@cviviers Thank you for your answer.

Using my original ply file, the dimeter measures about 3.7m. But this is different from the actual size.

So I multiplied it by 0.001 and did scaling. Will this have a big impact on ACC?

If so, how can I increase ACC when scalding?

Thanks

**Comment by cviviers** [comment]
Given that you already get some results for the 5cm 5 degree metric, makes it seem that the sizes might already be okay. The model is just not that accurate yet. Relax the metric [here](https://github.com/cviviers/YOLOv5-6D-Pose/blob/6b982c6043bb41ab53da804e8d09300ed5204261/test.py#L307). Maybe try a 20pixel metric and 30% of the object or something. 

You should have the .ply file in meters. Or if you read the data scale it there (which I think it what you are doing). I'm assuming the object is 3.7 cm? so it should read "Acc using 0.037 vx 3D Transformation"

**Comment by lsy-92** [comment]
When I use the model in a real robot, if i don't set it to the real size, doesn't it not test properly?

**Comment by lsy-92** [comment]
I use A100 gpus. but it does not use torch 1.9.1. so Metric does not work i think.

**Comment by cviviers** [comment]
I don't quite understand. Do you not know how large the object is?

**Comment by lsy-92** [comment]
I already know. but there's the difference between .ply's diam and real diam.

**Comment by cviviers** [comment]
Can you change the .ply diam to match the real diam? and store it in the .ply in meters

**Comment by lsy-92** [comment]
The unit is in meters, but there is a difference of 0.001 from the actual size. So I did scaling.

And if it's more than torch 1.9.1 version, can there be a problem with the metric calculation?

**Comment by cviviers** [comment]
No I think the way the metric is being calculated is correct. I've treated many objects with it. I also don't think the issue is because of the pytorch version number. 

Can you share the first coordinate of your object? As it is saved in the .ply file

**Comment by lsy-92** [comment]
@cviviers  

This is scaled ply file.
ply
format ascii 1.0
comment Created in Blender version 4.1.1
element vertex 54323
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 58046
property list uchar uint vertex_indices
end_header
0.00090872805 -0.00020112543 -0.01881535 0.6141107 -0.10092345 -0.7827404 0.78308 0.9967

This is original ply file.
ply
format ascii 1.0
comment Created in Blender version 4.1.1
element vertex 54323
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 58046
property list uchar uint vertex_indices
end_header
-0.9087257 -18.815325 -0.20112535 -0.61411226 -0.7827414 -0.10092347 0.78308 0.9967

**Comment by cviviers** [comment]
Yes, this is what I expected. When you created the object in blender you were just using the default units. There the units do not really correspond to anything. So to this codebase, the "original" ply would be interpreted as an object that is 18.825 meters wide for example.

Can you use the scaled object in all the experiments? How big is your object in real life (not in blender)? Store the real life size in the ply file in meters. So if the object is a 20 cm cube, then the top coordinate would be 0.1 0.1 0.1 and bottom would be -0.1 -0.1 -0.1

**Comment by lsy-92** [comment]
Can I ask for a detailed explanation?

Are both files wrong?

Then, will there be a problem when creating a dataset from the obj file?

**Comment by lsy-92** [comment]
I realized my problem.

If i use pnp, acc is almost 0.
but if i use pnpRANSAC, acc is almost 99.

Is the reason why this problem is happening because of my ply file?

Thanks.

**Comment by lsy-92** [comment]
In order to implement multi-object detection, does the dataset need to be multi-object?

I'm currently making an image with multi-object in the code, but I'm having a hard time because the prediction and label objects are different

**Comment by cviviers** [comment]
I think it will be good to train with some images with multiple objects in them. Getting the 2D keypoint predictions and its evaluation code should be quite straightforward. however getting the 3D evaluation code working might be a bit tricky. I think you will have to loop over all the ground truth objects in the image and evaluate them with respect to each prediction, and then only use the best prediction for each object. There should be some best practices for this that you can borrow from the object detection work, since there you also have multiple objects in an image

**Comment by cviviers** [comment]
Hi @lsy-92,

Nice to see the publication coming from your work. Congratulations! 🥇 
Will you be doing any further research on the topic? 

Maybe we can close the issue now that you have the paper published

**Comment by licong0903** [comment]
> 嗨，感谢您的重播。对于蒙版，我通过分割我的对象获得了它，但我仍然对 3D BBox 有问题，我让它从我的对象上移了一点。请问你从哪里获得姿势，将 3D BBox 投影到 2D 图像上？
